### ISSUE TITLE
Downgrade from 5.8.10

### ISSUE THREAD

**Issue by unidevel** [NiLuJe/KindleTool#12]
Hi, I have a KV with version 5.8.10, I want to downgrade it without taking it apart, but seems the downgrade guide doesn't work for me.

I noticed the firmware update_KV_5.5.0_initial.bin always disappear when I disconnect the USB. 

So next time I did not to disconnect USB, and long press the power button to let it reboot without disconnect, seems it can flash the firmware, however, it report me ERROR 16 after flash, and it let me reboot to my 5.8.10 without problem.

Then I enable the logging, I found something interesting

70828:060038 [    5.069795] <4>[    6.493223] ERROR:bundle/unbundle_wario.c:1566:do_unbundle():do_unbundle: FB02 bundle could not be applied over FB03
170828:060038 [    5.069828] <4>[    6.493679] INFO:bundle/unbundle_wario.c:2078:unbundle():No uboot image found! skipping uboot installation.
170828:060038 [    5.069859] <4>[    6.493730] ERROR:update.c:262:update_os():Could not unbundle /mnt-us/update_KV_5.5.0_initial.bin,error_code=16
170828:060038 [    5.069890] <4>[   35.644480] /mnt-us/update_KV_5.5.0_initial.bin MD5SUM: f7c8905ea993fef902be82b70a98542a
170828:060038 [    5.069906] <4>[   35.644638] INFO:update.c:43:remove_file_ll():removing /mnt-us/update_KV_5.5.0_initial.bin

Seems the update_KV_5.5.0_initial.bin packaged with "recovery"(FB02) option, and seemds 5.8.10 requires "recovery2"(FB03), so I wonder if the downgrade image repacked with recovery2 option, then it may work.

**Comment by NiLuJe** [comment]
Been away for quite a while, so take that with a grain of salt:

Recovery v2 bundles are signed, so, nope, you can't repack an official update that way and get it to pass the initramfs updater signature checks.

**Comment by unidevel** [comment]
I see, thanks !

**Comment by iddq** [comment]
Which updater should be patched to accept FB02 images?
