### ISSUE TITLE
Update failed when trying to execute script file by OTA package

### ISSUE THREAD

**Issue by Lynnette177** [NiLuJe/KindleTool#22]
Currently my Kinlde updated itself to newest firmware result the ;log command becoming invalid.
I'm trying to repair this command, using a emergency.sh script file.
So I packed the file into a .bin firmware, using this command
`kindletool create ota2 --device paperwhite4 -O /path/to/emergency.sh  /path/to/update_emergency.bin`
After doing this, I can click "Update your kindle" button in kindle's settings. However, then, "Update failed please press power button to reboot" appears and the script file is not executed.
Can you give me some hint on that?

**Comment by NiLuJe** [comment]
Check how hotfix updates are packaged (i.e., with `-O`).
