### ISSUE TITLE
How do I upgrade Kindle DX Graphite 3.3 to higher version ?

### ISSUE THREAD

**Issue by cppexpert** [NiLuJe/KindleTool#9]
I apologize but I don't know where else to ask and you seem most experience person in the field.

I'm owner of Kindle DX Graphite which I believe had firmware 2.5 as latest one. Some time in 2010 I manually patched Kindle Keyboard firmware v3.3 (611680021) to make it install on DX and I don't remember how I did it. The reason for that was issues of rendering Cyrillic PDFs on original firmware. 3.3 got installed but as you know recently Amazon changed certificates so my devices stopped connecting to 3G. Now I can't roll back to 2.5.8.

So I just took this
https://s3.amazonaws.com/G7G_FirmwareUpdates_WebDownloads/Update_kindle_3.4_B00A.bin

extracted it using your tool and repackaged by calling 

```
./kindletool create ota -d dxg frmwr34 Update_kindle_3.4_B009.bin
```

the update was recognized by the device but installation failed.

Could you suggest me how to pinpoint the issue and install it ? Maybe I'm missing  something obvious.

Thank you!

**Comment by NiLuJe** [comment]
No idea, sorry. It's likely to be much, much more complex than that, though.

(And, yeah, definitely the wrong place, try opening a thread on the MR Kindle Dev forum).
